apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/alexandruvidu/ci_cd_lab@sha256:bbd4372a61b2cd834443142570dcfda752baf704896ff8987fd4a52b9be9c8a2
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
